parameters:
    smile_ez_tools.contenttypegroup.service.class: Smile\EzToolsBundle\Service\ContentTypeGroup
    smile_ez_tools.contenttype.service.class: Smile\EzToolsBundle\Service\ContentType
    smile_ez_tools.content.service.class: Smile\EzToolsBundle\Service\Content
    smile_ez_tools.role.service.class: Smile\EzToolsBundle\Service\Role

services:
    smile_ez_tools.contenttypegroup.service:
        class: %smile_ez_tools.contenttypegroup.service.class%
        arguments: [@ezpublish.api.repository]
        calls:
            - [setAdminID, [%smile_ez_tools.adminid%]]

    smile_ez_tools.contenttype.service:
        class: %smile_ez_tools.contenttype.service.class%
        arguments: [@ezpublish.api.repository]
        calls:
            - [setAdminID, [%smile_ez_tools.adminid%]]

    smile_ez_tools.content.service:
        class: %smile_ez_tools.content.service.class%
        arguments: [@ezpublish.api.repository]
        calls:
            - [setAdminID, [%smile_ez_tools.adminid%]]

    smile_ez_tools.role.service:
        class: %smile_ez_tools.role.service.class%
        arguments: [@ezpublish.api.repository]
        calls:
            - [setAdminID, [%smile_ez_tools.adminid%]]
